### ISSUE TITLE
rcopenstack-neutron-ovs-cleanup required before reboot

### ISSUE THREAD

**Issue by tpatzig** [sap-oc/cookbook-openstack-network#5] opened 2017-03-13 16:33 UTC
On our network nodes an `rcopenstack-neutron-ovs-cleanup`was required prior to the reboot, to have network working, after the node starts, otherwise it hung up in crowbar_join.
@seife please provide more details from the maintenance, if you have

**Comment by vuntz** [comment] 2017-05-10 08:31
I think this is a duplicate of https://github.com/sap-oc/crowbar-core/issues/24

**Closed as completed by vuntz** 2017-05-10 08:31 UTC
